# Copyright (c) 2026 The STE||AR Group
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Reusable workflow for configuring and building HPX on Windows with ClangCL.

on:
    workflow_call:
        inputs:
            build-type:
                required: true
                type: string
            cmake-additional-options:
                required: false
                type: string
                default: ""
            build-targets:
                required: false
                type: string
                default: "ALL_BUILD"
            test-regex:
                required: false
                type: string
                default: "tests.examples"
            exclude-test-regex:
                required: false
                type: string
                default: ""

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6
    - uses: jwlawson/actions-setup-cmake@v2.0

    - name: Write vcpkg.json
      run: |
        echo '{
          "dependencies": [
            "boost",
            "hwloc",
            "asio"
          ]
        }' > vcpkg.json

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      id: runvcpkg
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'
        vcpkgGitCommitId: 8b1c07e64192e9269d54f85a4381816aefca52e0

    # - name: Install dependencies
    #   run: |
    #     md C:\projects
    #     $client = new-object System.Net.WebClient
    #     $client.DownloadFile("https://rostam.cct.lsu.edu/download/builder/vcpkg-export-hpx-dependencies-2024.7z","C:\projects\vcpkg-export-hpx-dependencies.7z")
    #     7z x C:\projects\vcpkg-export-hpx-dependencies.7z -y -oC:\projects\vcpkg
    - name: Configure
      shell: bash
      run: |
          cmake . -Bbuild -G'Visual Studio 17 2022' -T clangcl \
              -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
              -DCMAKE_TOOLCHAIN_FILE='${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake' \
              -DHPX_WITH_FETCH_ASIO=ON \
              -DHPX_WITH_ASIO_TAG=asio-1-34-2 \
              -DHPX_WITH_EXAMPLES=ON \
              -DHPX_WITH_TESTS=ON \
              -DHPX_WITH_TESTS_EXAMPLES=ON \
              -DHPX_WITH_TESTS_UNIT=ON \
              -DHPX_WITH_DEPRECATION_WARNINGS=OFF \
              -DHPX_WITH_TESTS_MAX_THREADS_PER_LOCALITY=2 \
              -DHPX_WITH_CHECK_MODULE_DEPENDENCIES=ON \
              ${{ inputs.build-type == 'Debug' && '-DHPX_COROUTINES_WITH_SWAP_CONTEXT_EMULATION=ON -DHPX_WITH_VERIFY_LOCKS=ON -DHPX_WITH_VERIFY_LOCKS_BACKTRACE=ON' || '' }} \
              ${{ inputs.cmake-additional-options }}
    - name: Build
      shell: bash
      run: |
          cmake --build build --config ${{ inputs.build-type }} \
          --target ALL_BUILD \
          -- -maxcpucount:2 -verbosity:minimal -nologo
    - name: Install
      shell: bash
      run: |
          cmake --install build --config ${{ inputs.build-type }}
    - name: Test
      shell: bash
      run: |
          EXCLUDE_REGEX=$(grep -v  -e ^# -e ^$ .github/workflows/excluded-tests-windows.txt | paste -sd'|')
          if [ -n "${{ inputs.exclude-test-regex }}" ]; then
            EXCLUDE_REGEX="${EXCLUDE_REGEX}|${{ inputs.exclude-test-regex }}"
          fi
          ctest \
            --test-dir build \
            --build-config ${{ inputs.build-type }} \
            --output-on-failure \
            --build-config ${{ inputs.build-type }} \
            --tests-regex ${{ inputs.test-regex }} \
            --exclude-regex "${EXCLUDE_REGEX}"
