# Copyright (c) 2024 Vedant Nimje
#
# SPDX-License-Identifier: BSL-1.0
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

name: Linux CI (Debug) with Benchmark Test

on: [pull_request]

# Cancel previous in-progress runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-with-nanobench:
    uses: ./.github/workflows/reusable/build-ubuntu.yml
    with:
      build-type: Debug
      cmake-additional-options: "-DHPX_WITH_NANOBENCH=ON"
      build-targets: "tests.performance.modules.segmented_algorithms.minmax_element_performance"
      skip-tests: true
      post-run-command: |
        cd build
        ./bin/minmax_element_performance_test
        ./bin/minmax_element_performance_test --detailed_bench

  build-without-nanobench:
    uses: ./.github/workflows/reusable/build-ubuntu.yml
    with:
      build-type: Debug
      cmake-additional-options: "-DHPX_WITH_NANOBENCH=OFF"
      build-targets: "tests.performance.modules.segmented_algorithms.minmax_element_performance"
      skip-tests: true
      post-run-command: |
        cd build
        ./bin/minmax_element_performance_test
        ./bin/minmax_element_performance_test --detailed_bench
